### ISSUE TITLE
[BUG] UI overflow

### ISSUE THREAD

**Issue by SirusCodes** [preetjdp/YouOweMe#17]
**Describe the bug**
UI bugs

**To Reproduce**
Tap on any Text field

**Screenshots**
![name page](https://user-images.githubusercontent.com/50910066/79351304-243b4300-7f56-11ea-9e01-5e48b4b442cb.png)
![otp page](https://user-images.githubusercontent.com/50910066/79351308-256c7000-7f56-11ea-9539-a8e33f63b79d.png)

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone max pro m2
 - OS: Android 9

**Comment by preetjdp** [comment]
Closing with https://github.com/preetjdp/YouOweMe/pull/18
