### ISSUE TITLE
[NEW IDEA] States of an Owe

### ISSUE THREAD

**Issue by preetjdp** [preetjdp/YouOweMe#22]
**Is your feature request related to a problem? Please describe.**
The idea to define a clear set of state a Owe can be in, to better handle its existence and show it in the UI.

**Describe the idea / solution you'd like**
In terms of graphql the solution should be in the lines of this https://typegraphql.com/docs/enums.html

The current enums in my mind are:
``` typescript
enum OweState {
    Opened,
    Declined,
    Delayed,
    Acknowledged,
    Paid
}
```

**Additional context**
This will be to track the state of a owe (is it paid, has the person acknowledged is, is it delayed, etc).
Another very important thing is it should be very flexible, easy to add new enums.

**Comment by preetjdp** [comment]
@pal-codes Thoughts on going this way? Am I missing any Enums?
@SirusCodes Would Like to hear your thoughts on this.

**Comment by pal-codes** [comment]
Can use definitive words to describe an Owe's life cycle better.

**Comment by SirusCodes** [comment]
Yes perfect can't, add anything else.
